# Generated by Django 3.1.4 on 2020-12-31 03:01

from django.db import migrations, models
import win_parser.models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to=win_parser.models.user_directory_path)),
            ],
        ),
    ]
