# Generated by Django 3.1.4 on 2020-12-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/'),
        ),
    ]
