# Generated by Django 3.1.4 on 2020-12-31 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0003_auto_20201230_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsconfigmodel',
            name='txt',
            field=models.FileField(default=django.utils.timezone.now, upload_to='txts'),
            preserve_default=False,
        ),
    ]
