# Generated by Django 3.1.4 on 2020-12-31 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0004_windowsconfigmodel_txt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
