# Generated by Django 3.1.4 on 2020-12-31 04:22

from django.db import migrations, models
import win_parser.models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0005_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsconfigmodel',
            name='txt',
            field=models.FileField(upload_to=win_parser.models.user_directory_path),
        ),
    ]
