# Generated by Django 3.1.4 on 2021-01-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0007_auto_20210108_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsconfigmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
