# Generated by Django 3.1.4 on 2021-01-13 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('win_parser', '0008_windowsconfigmodel_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='WindowsConfigModel',
            new_name='WindowsConfigFile',
        ),
    ]
