# Generated by Django 3.1.4 on 2021-01-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0009_auto_20210112_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowsConfig',
        ),
    ]
