# Generated by Django 3.1.4 on 2021-01-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0011_windowsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsconfig',
            name='hardware',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='NetworkAdapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_adapter', models.CharField(blank=True, max_length=128)),
                ('windows_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='win_parser.windowsconfig')),
            ],
        ),
    ]
