# Generated by Django 3.1.4 on 2021-01-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0012_auto_20210112_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkAdapter',
        ),
    ]
