# Generated by Django 3.1.4 on 2021-01-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0013_delete_networkadapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsconfig',
            name='network_adapters',
            field=models.TextField(blank=True),
        ),
    ]
