# Generated by Django 3.1.4 on 2021-01-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0014_windowsconfig_network_adapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsconfig',
            name='account_lockout_policies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='admins',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='all_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='audit_policies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='default_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='disabled_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='gpresult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='inactive_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='listening_ports',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='network_wlans',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='password_policies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='privilege_rights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='programs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='rdp_security_level',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='registry_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='screen_saver_timeout',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='security_updates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='time_peer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='time_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='windowsconfig',
            name='users',
            field=models.TextField(blank=True),
        ),
    ]
