# Generated by Django 3.1.4 on 2021-01-13 03:33

import django.core.validators
from django.db import migrations, models
import win_parser.models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0015_auto_20210112_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsconfigfile',
            name='config_file',
            field=models.FileField(upload_to=win_parser.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
