# Generated by Django 3.1.4 on 2021-01-13 03:36

from django.db import migrations, models
import win_parser.models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0016_auto_20210112_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsconfigfile',
            name='config_file',
            field=models.FileField(upload_to=win_parser.models.user_directory_path),
        ),
    ]
