# Generated by Django 3.1.4 on 2021-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_parser', '0017_auto_20210112_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsconfig',
            name='domain_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
